#include <furi.h>
#include <furi_hal.h>
#include <furi_hal_power.h>
#include <applications/services/power/power_service/power.h>
#include <furi_hal_gpio.h>
// These are in <firmware>/lib/stm32wb_hal/Inc if you are curious
#include <stm32wbxx_ll_tim.h>
#include <stm32wbxx_ll_gpio.h>

#include <gui/gui.h>
#include <gui/view.h>
#include <gui/view_dispatcher.h>
#include <gui/modules/byte_input.h>

#include "led_driver.h" // Derek Jamison's LED driver library

/* generated by fbt from .png files in images folder */
//#include <avs2026leddemo_icons.h>
#define TAG "AVS2026LEDDEMO"

/*
 * Main application structure.
 * Effectively, "global variables" a'la Flipper.
*/
typedef struct {
    // Power.
    Power* power;

    // GPIO pins
    GpioPin gpio_pa7; // we use this for PWM
    GpioPin gpio_pb2; // we use this for WS2812 led madness.

    // LED driver instance
    LedDriver* led_driver;

    uint32_t current_colour; // 0x00RRGGBB
    uint32_t current_pwm_value; // Store the current PWM value for brightness control (see docs)
    uint32_t byte_input_value; // This is the variable we are setting in ByteInput

    // GUI-related stuff
    Gui* gui; // this is the GUI instance
    ViewDispatcher* view_dispatcher; // this drives the screen
    View* byte_input_view; // this is the  ByteInput view module
    ByteInput* byte_input;
} main_app_structure;

// This is to access the main app structure from callback functions.
static main_app_structure* static_pointer_to_main_app_structure;

/*
 * Allocate stuff and initialise default values.
*/
void allocate_things(main_app_structure* context) {
    // Set some global variables to default values
    context->current_colour = 0x00FFFFFF; // Start with all white
    context->current_pwm_value = 1025; // See docs: inverted dimming, limited range.
    context->byte_input_value = 0xFFFFFFFF; // corresponding value for default setup.

    // Power, to see if we are charging.
    context->power = furi_record_open(RECORD_POWER);


    // We use this one for PWM
    context->gpio_pa7.port = GPIOA;
    context->gpio_pa7.pin = LL_GPIO_PIN_7;
    // We use this one for WS2812
    context->gpio_pb2.port = GPIOB;
    context->gpio_pb2.pin = LL_GPIO_PIN_2;

    // Allocate the LED driver
    context->led_driver = led_driver_alloc(2, &context->gpio_pb2); // 2 LEDs, using PB2

    // Set up the GUI
    context->gui = furi_record_open(RECORD_GUI);
    context->view_dispatcher = view_dispatcher_alloc();
    context->byte_input = byte_input_alloc();


}

/*
 * Free the allocated stuff.
 * THE ORDER OF HOW YOU DO THIS MATTTERS A LOT!
 * Not necessarily in reverse on how it was allocated,
 * but more of a walking backwards on the dependencies.
*/
void free_things(main_app_structure* context) {
    // GUI:
    view_dispatcher_stop(context->view_dispatcher); // This should have already been called.

    view_dispatcher_remove_view(context->view_dispatcher, 0); // view_id 0 for our ByteInput view);
    // byte_input (and its view) depends on the...
    byte_input_free(context->byte_input);
    FURI_LOG_D(TAG, "ByteInput freed.");
    // view_dispatcher depends on the...
    view_dispatcher_free(context->view_dispatcher);
    FURI_LOG_D(TAG, "ViewDispatcher freed.");
    // Main GUI thing
    furi_record_close(RECORD_GUI); // and the GUI depends on nothing.
    FURI_LOG_D(TAG, "GUI freed.");
    // Power:
    furi_record_close(RECORD_POWER);
    FURI_LOG_D(TAG, "Power record closed.");

    // LED driver:
    led_driver_free(context->led_driver);
    FURI_LOG_D(TAG, "LED driver freed.");

}

/*
 * Initialise hardware: 5V, PWM and WS2812
*/

void init_hardware(main_app_structure* context) {
    /*
     * Start with the 5V supply, but only if we are running on battery.
    */

    uint8_t retries = 5;
    PowerInfo power_info;
    power_get_info(context->power, &power_info);


    if(power_info.is_charging)
    {
         FURI_LOG_I(TAG, "External power supply detected, 5V already is enabled.");
    }
    else
    {
        while(retries > 0)
        {
            if(furi_hal_power_enable_otg())
            {
                break; // if success, break out of the while loop
            }
            else
            {
                FURI_LOG_W(TAG, "Failed to enable 5V power, retrying... (%d retries left)", retries);
            }
            retries--;
        }
        if(!retries)
        {
            FURI_LOG_E(TAG, "Failed to enable 5V power after multiple attempts. It may still work, when the USB power is connected. Proceeding for now.");
            //return; // or handle this error as appropriate
        }
    }

    /*
     * Some good old-fashioned low-level GPIO banging.
    */

    // Enable the timer bus
    furi_hal_bus_enable(FuriHalBusTIM1);

    // Set PA7: Alternate Function push-pull, assign timer 1
    furi_hal_gpio_init_ex(&context->gpio_pa7, GpioModeAltFunctionPushPull, GpioPullNo, GpioSpeedVeryHigh, GpioAltFn1TIM1);

    // Set prescaler to 0
    LL_TIM_SetPrescaler(TIM1, 0);

    // Set period register (ARR) to 1279. This controls the PWM frequency.
    LL_TIM_SetAutoReload(TIM1, 1279);

    // Set the Output Compare hardware to PWM mode
    LL_TIM_OC_SetMode(TIM1, LL_TIM_CHANNEL_CH1, LL_TIM_OCMODE_PWM1);
    // This was difficult to find.
    LL_TIM_CC_EnableChannel(TIM1, LL_TIM_CHANNEL_CH1N); // Use CH1N for PA7
    // Enable output
    LL_TIM_EnableAllOutputs(TIM1);
    // Set duty cycle (1025/1280 = 80%)
    LL_TIM_OC_SetCompareCH1(TIM1, 1025);


    // Start the counter we tirelessly set up above:
    LL_TIM_EnableCounter(TIM1);

    /*
     * WS2812 LED modules.
     * These are done by the driver, here we just send some default values out.
    */

    // We have 2 LEDs.
    led_driver_set_led(context->led_driver, 0, context->current_colour);
    led_driver_set_led(context->led_driver, 1, context->current_colour);

    // Send the info.
    led_driver_transmit(context->led_driver, false);
}

/*
 * Stop hardware: WS2812, PWM and 5V.
*/
void stop_hardware(main_app_structure* context) {
    // Turn the LEDs off
    led_driver_set_led(context->led_driver, 0, 0x00000000);
    led_driver_set_led(context->led_driver, 1, 0x00000000);
    led_driver_transmit(context->led_driver, false);

    // Disable PWM, set the pin to input, and disable furi hal for timer1.
    LL_TIM_DisableCounter(TIM1);
    //furi_hal_gpio_init_simple(&context->gpio_pa7, GpioModeInput);
    LL_GPIO_SetPinMode(context->gpio_pa7.port, context->gpio_pa7.pin, LL_GPIO_MODE_INPUT);
    furi_hal_bus_disable(FuriHalBusTIM1);

    // Disable the 5V supply
     if(furi_hal_power_is_otg_enabled())
    {
        // if we indeed have power, kill it gracefully.
        furi_hal_power_disable_otg();
    }
}




/*
 * GUI button press callback function.
 * If you modify any value in the ByteInput, or press 'save', this function is triggered.
 * Here, we recalculate the PWM values, and send the LED driver the new colour and brightness info.
*/

void update_values_from_gui(void* context) {
    /*
     * If we got here, we have some minimal processing to do:
     * Disassemble the viewDispatcher's byte_input_value.
     * The RGB stuff is simple, just bitwise and with 0x00FFFFFF.
     * The PWM stuff is not. See docs, section 'High level GUI - ViewDispatcher, ByteInput, and callback structure' for details.
     * There is also an endianness difference here:
     * -In this implementation, the format is 0xPPRRGGBB, where PP is the PWM value and the rest is RGB.
     * -In ByteInput, it's treated as a 4-byte array, so the first byte is the least significant one, which means that the format is 0xBBGGRRPP, where PP is the PWM value and the rest is RGB.
    */

    // Get access to the main app structure without making the poor thing crash.
    main_app_structure* app_context = (main_app_structure*) context;


    // There is a brown-out reset issue, so when the GUI is set to 0xFF, the PWM value must not be 1 to cut power totally. Original value was 1025.
    uint32_t full_pwm_value = 1022; // Corresponds to full brightness, because we scale from 5V to 3.3V with an active low input.

    // Do some hacking with the PWM value.
    uint32_t pwm_value_from_gui = (app_context->byte_input_value) & 0x000000FF; // Last byte in ByteInput, which is the leftmost in the GUI
    // Invert this value.
    pwm_value_from_gui = 255 - pwm_value_from_gui;
    // Make sure that we are staying within limits. It's unsigned int.
    if(pwm_value_from_gui > 255) {
        pwm_value_from_gui = 255;
    }

    // Scale this value, if necessary.
    pwm_value_from_gui = pwm_value_from_gui * 1; // Do nothing with this, for now.
    app_context->current_pwm_value = pwm_value_from_gui + full_pwm_value;

    // Sanity check on PWM value:
    if(app_context->current_pwm_value > 1280) {
        app_context->current_pwm_value = 1280;
    }

    // The byte input value is 0xBBGGRRPP, we want to convert this to 0x00RRGGBB for the LED driver.
    // Take the red byte, shift it left by 8 bits.
    // Take the green byte, shift it right by 8 bits.
    // Take the blue byte, shift it right by 24 bits.
    uint32_t rgb_value_from_gui = ((app_context->byte_input_value & 0x0000FF00) << 8) | ((app_context->byte_input_value & 0x00FF0000) >> 8) | ((app_context->byte_input_value & 0xFF000000) >> 24);



    // Update the variable in the structure.
    app_context->current_colour = rgb_value_from_gui;
    //app_context->current_colour = app_context->byte_input_value;


    // So these are the values we are sending out:
    FURI_LOG_D(TAG, "GUI: 0x%08lX.", app_context->byte_input_value);
    FURI_LOG_D(TAG, "RGB: 0x%08lX.", rgb_value_from_gui);
    FURI_LOG_D(TAG, "PWM: 0x%08lX.", pwm_value_from_gui);

    //FURI_LOG_D(TAG, "Updating values from GUI: Byte PWM value: 0x%02ld, RGB value: 0x%06lX.", app_context->current_pwm_value, app_context->current_colour);



    // Set PWM to the reference 3.3V to make sure the second LED is capable of receiving the data.
    LL_TIM_OC_SetCompareCH1(TIM1, 0);

    // We wait something like 1 ms, to make sure that the LED actually has some time to power up
    furi_delay_ms(1); // Could be smaller...

    // Now we know that we have proper power, so:
    led_driver_set_led(app_context->led_driver, 0, app_context->current_colour);
    // Adjust both LEDs
    led_driver_set_led(app_context->led_driver, 1, app_context->current_colour); // keep this white
    led_driver_transmit(app_context->led_driver, false);

    // We wait for the transmission to finish, and then we dim
    furi_delay_ms(1); // Could be smaller...

    // and now, we set the power wherever the user (most probably, me) wanted it.
    LL_TIM_OC_SetCompareCH1(TIM1, app_context->current_pwm_value);
}

/*
 * Navigation even, for the back button.
 * It does two things.
 * When pressed at first, then the ByteInput value is being reset to its default value.
 * If it is aready at the default value, then it stops ViewDispatcher, which effectively means exiting the app.
*/

bool back_button_navigation_event(void* context) {
    UNUSED(context);


    //main_app_structure* app_context = (main_app_structure*) context;
    main_app_structure* app_context = static_pointer_to_main_app_structure;

    if(app_context->byte_input_value != 0xFFFFFFFF) {
        // If the value is not the default one, reset it to the default one.
        app_context->byte_input_value = 0xFFFFFFFF;
        update_values_from_gui(app_context); // and update the hardware with this new value.
        FURI_LOG_D(TAG, "Back button pressed, resetting values to default. Press again to exit.");
        return true; // and consume the event, so that it doesn't trigger the view dispatcher to stop.
    }
    else {
        // If the value is already at the default one, we want to exit the app, so we stop the view dispatcher.
        FURI_LOG_D(TAG, "Back button pressed again, exiting app.");
        view_dispatcher_stop(app_context->view_dispatcher);
        return false; // and don't consume the event, so that it can trigger the view dispatcher to stop.
    }
}


/*
 * Start GUI, with callbacks
*/
void run_gui(main_app_structure* context) {

    // Attach to GUI:
    view_dispatcher_attach_to_gui(context->view_dispatcher, context->gui, ViewDispatcherTypeFullscreen);

    // Custom callback for back button:
    view_dispatcher_set_navigation_event_callback(context->view_dispatcher, back_button_navigation_event);

    // Get the view
    context->byte_input_view = byte_input_get_view(context->byte_input);

    // Add said view to view dispatcher
    view_dispatcher_add_view(context->view_dispatcher, 0, context->byte_input_view); // view_id 0 for our ByteInput view);

    FURI_LOG_D(TAG, "ByteInput view added to view dispatcher.");

    byte_input_set_result_callback(context->byte_input, // The ByteInput module. We use only 1, but can be many.
        update_values_from_gui, // Call this when pressing 'save' in the ByteInput view
        update_values_from_gui, // Call this when there is any change in the values
        context, // We will toss the main app structure to the callback.
        (uint8_t*)&context->byte_input_value, // This is clever: we use a uint32_t as a 4-byte array
        4); // This is the number of bytes to be displayed.

    FURI_LOG_D(TAG, "Now switching to view");

    // Switch to view
    view_dispatcher_switch_to_view(context->view_dispatcher, 0); // view_id 0 for our ByteInput view);

    // Blastoff!
    view_dispatcher_run(context->view_dispatcher);

}



int32_t avs2026leddemo_main(void* p) {
    UNUSED(p);

    FURI_LOG_D(TAG, "Starting app");
    // Allocate memory
    main_app_structure* context = malloc(sizeof(main_app_structure));
    static_pointer_to_main_app_structure = context; // Set the static pointer to the main app structure, so that we can access it from callbacks.
    allocate_things(context);
    FURI_LOG_D(TAG, "Memory allocated and initialised");

    // Initialise hardware
    init_hardware(context);
    FURI_LOG_D(TAG, "Hardware initialised, you should see stuff happening with an oscilloscope.");



    // Run the GUI.
    run_gui(context);


    // for now, add a 10-second delay here, to give you time to hook up the oscilloscope and see the PWM signal.
    // You should see a 3.3V signal with 80% duty cycle, which corresponds to the default value of 1025 in the code.
    //furi_delay_ms(10000);

    // When the user presses 'Back' on the Flipper, the view dispatcher will stop, and we will continue with the code below.


    // Stop hardware.
    stop_hardware(context);

    // Free memory
    free_things(context);
    furi_delay_ms(100); // allow the hardware to die
    free(context);

    FURI_LOG_I(TAG, "Exiting app.");
    return 0;
}
